name: Run Django Tests

on:
    workflow_dispatch:

jobs:
    runtests:
      runs-on: ubuntu-latest
      environment: tests
      steps:
        - uses: actions/checkout@master

        - name: Setup Python version
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Create and start virtual environment
          run: |
            python3 -m venv venv
            source venv/bin/activate

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Run tests
          run: python polls-sample/mysite/manage.py test polls
        